apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      name: flaskport
      targetPort: {{ .Values.deployment.port }}
  type: LoadBalancer
