deployment:
        name: myecr
        image: 855051130134.dkr.ecr.eu-central-1.amazonaws.com/myecr
        tag: latest
        replicas: 1
        port: 5000

service:
        name: flaskapp-lb-svc
